pipeline {
    agent any

    stages {
        stage('init') {
            steps {
                echo 'This is sampath from F-17'
            }
        }
        
        stage('Build'){
            steps {
                echo 'Build from maven'
            }
        }
        stage('deploy'){
            
            steps {
                echo 'Deploy to staging area'
            }
        }
    }
}
