pipeline 
{
    agent any

    stages 
    {
        stage('Compile Stage') 
        {
            steps
             {
                withMaven(maven : 'LocalMaven')
                sh 'mvn clean compile'
             }
        }
        
        stage('Build and Testing stage')
        {
            steps 
            {
                withMaven(maven : 'LocalMaven')
                sh 'mvn test'
            }
        }
        stage('Deployment stage')
        {
            
            steps 
            {
                withMaven(maven : 'LocalMaven')
                sh 'mvn deploy'
            }
         }
    }
 }